### ISSUE TITLE
Qwen2转化llama格式，max_position_embeddings为什么是固定4096？

### ISSUE THREAD

**Issue by CxsGhost** [Minami-su/character_AI_open#2]
您好，我看到您的转换脚本中，将qwen2转成时max_position_embeddings使用4096而不是qwen2的原始长度，请问这样做的原因是什么？
![image](https://github.com/Minami-su/character_AI_open/assets/56266294/f461b5a5-7004-41f2-807c-10a47a211cf4)

**Comment by Minami-su** [comment]
> 您好，我看到您的转换脚本中，将qwen2转成时max_position_embeddings使用4096而不是qwen2的原始长度，请问这样做的原因是什么？ ![image](https://private-user-images.githubusercontent.com/56266294/346874391-f461b5a5-7004-41f2-807c-10a47a211cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTMzMzcsIm5iZiI6MTcyMDUxMzAzNywicGF0aCI6Ii81NjI2NjI5NC8zNDY4NzQzOTEtZjQ2MWI1YTUtNzAwNC00MWYyLTgwN2MtMTBhNDdhMjExY2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA4MTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMzRiYTQ3ZTYzOTc4OWE0ZDY3MmRlZjRkNDNmNWU1YTdjNWRlNDEyYmI3ZDJhMDJlZTVjZDM5ZjFiMTFkN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6vJxu00Esq2h0aiewX39uidW2ClZ4uGBwnEgPMNI2gc)

用原始长度可能会使模型生成速度变慢。

**Comment by CxsGhost** [comment]
原来如此。还想问下您是否观察到转换后的模型，在贪婪采样时，和原模型的输出不一致？

**Comment by Minami-su** [comment]
> 原来如此。还想问下您是否观察到转换后的模型，在贪婪采样时，和原模型的输出不一致？

没有观察，我只进行了huggingface llm leaderboard测评观察分值几乎一致

**Comment by CxsGhost** [comment]
好的，感谢您的回复！
